# Form implementation generated from reading ui file 'create.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateFailure(object):
    def setupUi(self, CreateFailure):
        CreateFailure.setObjectName("CreateFailure")
        CreateFailure.resize(378, 305)
        self.save_failure_button = QtWidgets.QPushButton(parent=CreateFailure)
        self.save_failure_button.setGeometry(QtCore.QRect(190, 120, 71, 31))
        self.save_failure_button.setObjectName("save_failure_button")
        self.cancel_failure_button = QtWidgets.QPushButton(parent=CreateFailure)
        self.cancel_failure_button.setGeometry(QtCore.QRect(190, 160, 71, 31))
        self.cancel_failure_button.setObjectName("cancel_failure_button")
        self.edit_tools_groupbox = QtWidgets.QGroupBox(parent=CreateFailure)
        self.edit_tools_groupbox.setGeometry(QtCore.QRect(190, 10, 181, 61))
        self.edit_tools_groupbox.setObjectName("edit_tools_groupbox")
        self.add_latex_button = QtWidgets.QPushButton(parent=self.edit_tools_groupbox)
        self.add_latex_button.setGeometry(QtCore.QRect(10, 30, 75, 24))
        self.add_latex_button.setObjectName("add_latex_button")
        self.add_image_button = QtWidgets.QPushButton(parent=self.edit_tools_groupbox)
        self.add_image_button.setGeometry(QtCore.QRect(100, 30, 71, 24))
        self.add_image_button.setObjectName("add_image_button")
        self.failure_preview_groupbox = QtWidgets.QGroupBox(parent=CreateFailure)
        self.failure_preview_groupbox.setGeometry(QtCore.QRect(10, 0, 171, 301))
        self.failure_preview_groupbox.setAutoFillBackground(False)
        self.failure_preview_groupbox.setObjectName("failure_preview_groupbox")
        self.failure_description_text = QtWidgets.QTextEdit(parent=self.failure_preview_groupbox)
        self.failure_description_text.setGeometry(QtCore.QRect(0, 20, 171, 281))
        self.failure_description_text.setObjectName("failure_description_text")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=CreateFailure)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 70, 101, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.add_tag_button = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.add_tag_button.setGeometry(QtCore.QRect(50, 150, 41, 21))
        self.add_tag_button.setObjectName("add_tag_button")
        self.tags_combobox = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.tags_combobox.setGeometry(QtCore.QRect(10, 20, 80, 24))
        self.tags_combobox.setObjectName("tags_combobox")
        self.tags_list = QtWidgets.QListWidget(parent=self.groupBox_3)
        self.tags_list.setGeometry(QtCore.QRect(10, 50, 81, 91))
        self.tags_list.setObjectName("tags_list")
        self.show_description_preview = QtWidgets.QPushButton(parent=CreateFailure)
        self.show_description_preview.setGeometry(QtCore.QRect(190, 80, 71, 31))
        self.show_description_preview.setObjectName("show_description_preview")
        self.failure_preview_groupbox.raise_()
        self.save_failure_button.raise_()
        self.cancel_failure_button.raise_()
        self.edit_tools_groupbox.raise_()
        self.groupBox_3.raise_()
        self.show_description_preview.raise_()

        self.retranslateUi(CreateFailure)
        QtCore.QMetaObject.connectSlotsByName(CreateFailure)

    def retranslateUi(self, CreateFailure):
        _translate = QtCore.QCoreApplication.translate
        CreateFailure.setWindowTitle(_translate("CreateFailure", "Dialog"))
        self.save_failure_button.setText(_translate("CreateFailure", "SAVE"))
        self.cancel_failure_button.setText(_translate("CreateFailure", "CANCEL"))
        self.edit_tools_groupbox.setTitle(_translate("CreateFailure", "Edit Tools"))
        self.add_latex_button.setText(_translate("CreateFailure", "LATEX"))
        self.add_image_button.setText(_translate("CreateFailure", "Image"))
        self.failure_preview_groupbox.setTitle(_translate("CreateFailure", "Failure Description"))
        self.groupBox_3.setTitle(_translate("CreateFailure", "Tags"))
        self.add_tag_button.setText(_translate("CreateFailure", "Add"))
        self.show_description_preview.setText(_translate("CreateFailure", "PREVIEW"))
