# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditFailure(object):
    def setupUi(self, EditFailure):
        EditFailure.setObjectName("EditFailure")
        EditFailure.resize(678, 390)
        self.edit_tools_groupbox = QtWidgets.QGroupBox(parent=EditFailure)
        self.edit_tools_groupbox.setEnabled(True)
        self.edit_tools_groupbox.setGeometry(QtCore.QRect(10, 310, 251, 71))
        self.edit_tools_groupbox.setObjectName("edit_tools_groupbox")
        self.add_latex_button = QtWidgets.QPushButton(parent=self.edit_tools_groupbox)
        self.add_latex_button.setGeometry(QtCore.QRect(10, 30, 101, 24))
        self.add_latex_button.setObjectName("add_latex_button")
        self.add_image_button = QtWidgets.QPushButton(parent=self.edit_tools_groupbox)
        self.add_image_button.setGeometry(QtCore.QRect(140, 30, 101, 24))
        self.add_image_button.setObjectName("add_image_button")
        self.failure_preview_groupbox = QtWidgets.QGroupBox(parent=EditFailure)
        self.failure_preview_groupbox.setGeometry(QtCore.QRect(320, 0, 301, 311))
        self.failure_preview_groupbox.setAutoFillBackground(False)
        self.failure_preview_groupbox.setObjectName("failure_preview_groupbox")
        self.failure_description_preview = QtWidgets.QTextEdit(parent=self.failure_preview_groupbox)
        self.failure_description_preview.setGeometry(QtCore.QRect(0, 20, 301, 291))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.failure_description_preview.setFont(font)
        self.failure_description_preview.setObjectName("failure_description_preview")
        self.failure_description_groupbox = QtWidgets.QGroupBox(parent=EditFailure)
        self.failure_description_groupbox.setGeometry(QtCore.QRect(10, 0, 301, 311))
        self.failure_description_groupbox.setAutoFillBackground(False)
        self.failure_description_groupbox.setObjectName("failure_description_groupbox")
        self.failure_description_text = QtWidgets.QTextEdit(parent=self.failure_description_groupbox)
        self.failure_description_text.setGeometry(QtCore.QRect(0, 20, 301, 291))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.failure_description_text.setFont(font)
        self.failure_description_text.setObjectName("failure_description_text")
        self.save_failure_button = QtWidgets.QPushButton(parent=EditFailure)
        self.save_failure_button.setGeometry(QtCore.QRect(420, 320, 91, 31))
        self.save_failure_button.setObjectName("save_failure_button")
        self.cancel_failure_button = QtWidgets.QPushButton(parent=EditFailure)
        self.cancel_failure_button.setGeometry(QtCore.QRect(520, 320, 91, 31))
        self.cancel_failure_button.setObjectName("cancel_failure_button")

        self.retranslateUi(EditFailure)
        QtCore.QMetaObject.connectSlotsByName(EditFailure)

    def retranslateUi(self, EditFailure):
        _translate = QtCore.QCoreApplication.translate
        EditFailure.setWindowTitle(_translate("EditFailure", "Dialog"))
        self.edit_tools_groupbox.setTitle(_translate("EditFailure", "Edit Tools"))
        self.add_latex_button.setText(_translate("EditFailure", "LATEX"))
        self.add_image_button.setText(_translate("EditFailure", "Image"))
        self.failure_preview_groupbox.setTitle(_translate("EditFailure", "(Preview)"))
        self.failure_description_groupbox.setTitle(_translate("EditFailure", "Failure Description"))
        self.save_failure_button.setText(_translate("EditFailure", "SAVE"))
        self.cancel_failure_button.setText(_translate("EditFailure", "CANCEL"))
