# Form implementation generated from reading ui file 'explorer.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FailureExplorer(object):
    def setupUi(self, FailureExplorer):
        FailureExplorer.setObjectName("FailureExplorer")
        FailureExplorer.resize(803, 728)
        FailureExplorer.setModal(True)
        self.filter_list_view = QtWidgets.QListView(parent=FailureExplorer)
        self.filter_list_view.setGeometry(QtCore.QRect(0, 10, 491, 421))
        self.filter_list_view.setObjectName("filter_list_view")
        self.failure_list_scrollbar = QtWidgets.QScrollBar(parent=FailureExplorer)
        self.failure_list_scrollbar.setGeometry(QtCore.QRect(480, 10, 16, 421))
        self.failure_list_scrollbar.setMouseTracking(False)
        self.failure_list_scrollbar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.failure_list_scrollbar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.failure_list_scrollbar.setObjectName("failure_list_scrollbar")
        self.failure_filters_groupbox = QtWidgets.QGroupBox(parent=FailureExplorer)
        self.failure_filters_groupbox.setGeometry(QtCore.QRect(500, 0, 291, 431))
        self.failure_filters_groupbox.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.failure_filters_groupbox.setObjectName("failure_filters_groupbox")
        self.deck_filter_group = QtWidgets.QGroupBox(parent=self.failure_filters_groupbox)
        self.deck_filter_group.setGeometry(QtCore.QRect(10, 20, 181, 51))
        self.deck_filter_group.setObjectName("deck_filter_group")
        self.deck_filter_combobox = QtWidgets.QComboBox(parent=self.deck_filter_group)
        self.deck_filter_combobox.setGeometry(QtCore.QRect(10, 20, 121, 24))
        self.deck_filter_combobox.setAccessibleName("")
        self.deck_filter_combobox.setObjectName("deck_filter_combobox")
        self.deck_filter_combobox.addItem("")
        self.tag_filter_group = QtWidgets.QGroupBox(parent=self.failure_filters_groupbox)
        self.tag_filter_group.setGeometry(QtCore.QRect(10, 80, 181, 51))
        self.tag_filter_group.setObjectName("tag_filter_group")
        self.tag_filter_combobox = QtWidgets.QComboBox(parent=self.tag_filter_group)
        self.tag_filter_combobox.setGeometry(QtCore.QRect(10, 20, 121, 24))
        self.tag_filter_combobox.setObjectName("tag_filter_combobox")
        self.tag_filter_combobox.addItem("")
        self.filter_date_combobox = QtWidgets.QGroupBox(parent=self.failure_filters_groupbox)
        self.filter_date_combobox.setGeometry(QtCore.QRect(10, 140, 181, 121))
        self.filter_date_combobox.setObjectName("filter_date_combobox")
        self.filter_date_from_combobox = QtWidgets.QGroupBox(parent=self.filter_date_combobox)
        self.filter_date_from_combobox.setGeometry(QtCore.QRect(20, 20, 121, 41))
        self.filter_date_from_combobox.setObjectName("filter_date_from_combobox")
        self.filter_from_date = QtWidgets.QDateEdit(parent=self.filter_date_from_combobox)
        self.filter_from_date.setGeometry(QtCore.QRect(0, 20, 121, 23))
        self.filter_from_date.setObjectName("filter_from_date")
        self.filter_date_to_combobox = QtWidgets.QGroupBox(parent=self.filter_date_combobox)
        self.filter_date_to_combobox.setGeometry(QtCore.QRect(20, 70, 121, 41))
        self.filter_date_to_combobox.setObjectName("filter_date_to_combobox")
        self.filter_to_date = QtWidgets.QDateEdit(parent=self.filter_date_to_combobox)
        self.filter_to_date.setGeometry(QtCore.QRect(0, 20, 121, 23))
        self.filter_to_date.setObjectName("filter_to_date")
        self.edit_selected_failure = QtWidgets.QPushButton(parent=FailureExplorer)
        self.edit_selected_failure.setGeometry(QtCore.QRect(10, 440, 111, 51))
        self.edit_selected_failure.setObjectName("edit_selected_failure")
        self.delete_selected_failure = QtWidgets.QPushButton(parent=FailureExplorer)
        self.delete_selected_failure.setGeometry(QtCore.QRect(130, 440, 111, 51))
        self.delete_selected_failure.setObjectName("delete_selected_failure")
        self.search_failures_button = QtWidgets.QPushButton(parent=FailureExplorer)
        self.search_failures_button.setGeometry(QtCore.QRect(390, 440, 101, 51))
        self.search_failures_button.setObjectName("search_failures_button")

        self.retranslateUi(FailureExplorer)
        QtCore.QMetaObject.connectSlotsByName(FailureExplorer)

    def retranslateUi(self, FailureExplorer):
        _translate = QtCore.QCoreApplication.translate
        FailureExplorer.setWindowTitle(_translate("FailureExplorer", "Failure Tracking Explorer"))
        self.failure_filters_groupbox.setTitle(_translate("FailureExplorer", "Filters"))
        self.deck_filter_group.setTitle(_translate("FailureExplorer", "Deck"))
        self.deck_filter_combobox.setCurrentText(_translate("FailureExplorer", "ALL"))
        self.deck_filter_combobox.setItemText(0, _translate("FailureExplorer", "ALL"))
        self.tag_filter_group.setTitle(_translate("FailureExplorer", "Tag"))
        self.tag_filter_combobox.setItemText(0, _translate("FailureExplorer", "ALL"))
        self.filter_date_combobox.setTitle(_translate("FailureExplorer", "Time"))
        self.filter_date_from_combobox.setTitle(_translate("FailureExplorer", "From"))
        self.filter_date_to_combobox.setTitle(_translate("FailureExplorer", "To"))
        self.edit_selected_failure.setText(_translate("FailureExplorer", "Edit Failure"))
        self.delete_selected_failure.setText(_translate("FailureExplorer", "Delete Failure"))
        self.search_failures_button.setText(_translate("FailureExplorer", "Search"))
