# Form implementation generated from reading ui file 'preview.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Preview(object):
    def setupUi(self, Preview):
        Preview.setObjectName("Preview")
        Preview.resize(400, 300)
        self.preview_box = QtWebEngineWidgets.QWebEngineView(parent=Preview)
        self.preview_box.setGeometry(QtCore.QRect(40, 30, 131, 171))
        self.preview_box.setUrl(QtCore.QUrl("about:blank"))
        self.preview_box.setObjectName("preview_box")

        self.retranslateUi(Preview)
        QtCore.QMetaObject.connectSlotsByName(Preview)

    def retranslateUi(self, Preview):
        _translate = QtCore.QCoreApplication.translate
        Preview.setWindowTitle(_translate("Preview", "Dialog"))
from PyQt6 import QtWebEngineWidgets
